name: workflow

on:
  push:
    tags:
      - '*.*.*'
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: './go.mod'
      - run: make build
      - run: make test
      - if: startsWith(github.ref, 'refs/heads/')
        run: curl https://proxy.golang.org/github.com/larscom/go-bitvavo/@v/${{ github.ref_name }}.info
